package bundesliga;


public class BundesligaMain {

    public static void main(String[] args) {

        createBlTeams();
        initBundesliga();
        addGames22();
        League bl_22 = League.getLeague("Bundesliga 22/23");
        Table table = bl_22.getTable(null, Table.TableType.BOTH);
        table.printEntries(table.getTableNaturalSorted());

        System.out.println("This is a debug Point");
    }
    
    public static void createBlTeams(){
        Team sge = new Team("Eintracht Frankfurt");
        Team fcu = new Team("1. FC Union Berlin");
        Team bmg = new Team("Borussia Mönchengladbach");
        Team wob = new Team("VfL Wolfsburg");
        Team boc = new Team("VfL Bochum");
        Team fca = new Team("FC Augsburg");
        Team bvb = new Team("Borussia Dortmund");
        Team vfb = new Team("VfB Stuttgart");
        Team koe = new Team("1. FC Köln");
        Team fcb = new Team("FC Bayern München");
        Team bsc = new Team("Hertha BSC");
        Team tsg = new Team("1899 Hoffenheim");
        Team svw = new Team("SV Werder Bremen");
        Team m05 = new Team("1. FSV Mainz 05");
        Team scf = new Team("SC Freiburg");
        Team b04 = new Team("Bayer Leverkusen");
        Team rbl = new Team("RB Leipzig");
        Team s04 = new Team("FC Schalke 04");
    }
    
    
    public static void initBundesliga(){
        League bl1_22 = new League("Bundesliga 22/23");
        bl1_22.addTeam("Eintracht Frankfurt");
        bl1_22.addTeam("1. FC Union Berlin");
        bl1_22.addTeam("Borussia Mönchengladbach");
        bl1_22.addTeam("VfL Wolfsburg");
        bl1_22.addTeam("VfL Bochum");
        bl1_22.addTeam("FC Augsburg");
        bl1_22.addTeam("Borussia Dortmund");
        bl1_22.addTeam("VfB Stuttgart");
        bl1_22.addTeam("1. FC Köln");
        bl1_22.addTeam("FC Bayern München");
        bl1_22.addTeam("Hertha BSC");
        bl1_22.addTeam("1899 Hoffenheim");
        bl1_22.addTeam("SV Werder Bremen");
        bl1_22.addTeam("1. FSV Mainz 05");
        bl1_22.addTeam("SC Freiburg");
        bl1_22.addTeam("Bayer Leverkusen");
        bl1_22.addTeam("RB Leipzig");
        bl1_22.addTeam("FC Schalke 04");
    }

    public static void addGames22(){
        new Game("Bundesliga 22/23", 1, "Eintracht Frankfurt", "FC Bayern München", "1:6"); 
        new Game("Bundesliga 22/23", 1, "1. FC Union Berlin", "Hertha BSC", "3:1"); 
        new Game("Bundesliga 22/23", 1, "Borussia Mönchengladbach", "1899 Hoffenheim", "3:1"); 
        new Game("Bundesliga 22/23", 1, "VfL Wolfsburg", "SV Werder Bremen", "2:2"); 
        new Game("Bundesliga 22/23", 1, "VfL Bochum", "1. FSV Mainz 05", "1:2"); 
        new Game("Bundesliga 22/23", 1, "FC Augsburg", "SC Freiburg", "0:4"); 
        new Game("Bundesliga 22/23", 1, "Borussia Dortmund", "Bayer Leverkusen", "1:0"); 
        new Game("Bundesliga 22/23", 1, "VfB Stuttgart", "RB Leipzig", "1:1"); 
        new Game("Bundesliga 22/23", 1, "1. FC Köln", "FC Schalke 04", "3:1"); 
        new Game("Bundesliga 22/23", 2, "SC Freiburg", "Borussia Dortmund", "1:3"); 
        new Game("Bundesliga 22/23", 2, "Bayer Leverkusen", "FC Augsburg", "1:2"); 
        new Game("Bundesliga 22/23", 2, "RB Leipzig", "1. FC Köln", "2:2"); 
        new Game("Bundesliga 22/23", 2, "1899 Hoffenheim", "VfL Bochum", "3:2"); 
        new Game("Bundesliga 22/23", 2, "Hertha BSC", "Eintracht Frankfurt", "1:1"); 
        new Game("Bundesliga 22/23", 2, "SV Werder Bremen", "VfB Stuttgart", "2:2"); 
        new Game("Bundesliga 22/23", 2, "FC Schalke 04", "Borussia Mönchengladbach", "2:2"); 
        new Game("Bundesliga 22/23", 2, "1. FSV Mainz 05", "1. FC Union Berlin", "0:0"); 
        new Game("Bundesliga 22/23", 2, "FC Bayern München", "VfL Wolfsburg", "2:0"); 
        new Game("Bundesliga 22/23", 3, "Borussia Mönchengladbach", "Hertha BSC", "1:0"); 
        new Game("Bundesliga 22/23", 3, "Borussia Dortmund", "SV Werder Bremen", "2:3"); 
        new Game("Bundesliga 22/23", 3, "Bayer Leverkusen", "1899 Hoffenheim", "0:3"); 
        new Game("Bundesliga 22/23", 3, "VfL Wolfsburg", "FC Schalke 04", "0:0"); 
        new Game("Bundesliga 22/23", 3, "FC Augsburg", "1. FSV Mainz 05", "1:2"); 
        new Game("Bundesliga 22/23", 3, "VfB Stuttgart", "SC Freiburg", "0:1"); 
        new Game("Bundesliga 22/23", 3, "1. FC Union Berlin", "RB Leipzig", "2:1"); 
        new Game("Bundesliga 22/23", 3, "Eintracht Frankfurt", "1. FC Köln", "1:1"); 
        new Game("Bundesliga 22/23", 3, "VfL Bochum", "FC Bayern München", "0:7"); 
        new Game("Bundesliga 22/23", 4, "SC Freiburg", "VfL Bochum", "1:0"); 
        new Game("Bundesliga 22/23", 4, "RB Leipzig", "VfL Wolfsburg", "2:0"); 
        new Game("Bundesliga 22/23", 4, "1. FSV Mainz 05", "Bayer Leverkusen", "0:3"); 
        new Game("Bundesliga 22/23", 4, "1899 Hoffenheim", "FC Augsburg", "1:0"); 
        new Game("Bundesliga 22/23", 4, "Hertha BSC", "Borussia Dortmund", "0:1"); 
        new Game("Bundesliga 22/23", 4, "FC Schalke 04", "1. FC Union Berlin", "1:6"); 
        new Game("Bundesliga 22/23", 4, "FC Bayern München", "Borussia Mönchengladbach", "1:1"); 
        new Game("Bundesliga 22/23", 4, "1. FC Köln", "VfB Stuttgart", "0:0"); 
        new Game("Bundesliga 22/23", 4, "SV Werder Bremen", "Eintracht Frankfurt", "3:4"); 
        new Game("Bundesliga 22/23", 5, "Borussia Dortmund", "1899 Hoffenheim", "1:0"); 
        new Game("Bundesliga 22/23", 5, "Bayer Leverkusen", "SC Freiburg", "2:3"); 
        new Game("Bundesliga 22/23", 5, "1. FC Union Berlin", "FC Bayern München", "1:1"); 
        new Game("Bundesliga 22/23", 5, "VfL Wolfsburg", "1. FC Köln", "2:4"); 
        new Game("Bundesliga 22/23", 5, "VfL Bochum", "SV Werder Bremen", "0:2"); 
        new Game("Bundesliga 22/23", 5, "VfB Stuttgart", "FC Schalke 04", "1:1"); 
        new Game("Bundesliga 22/23", 5, "Eintracht Frankfurt", "RB Leipzig", "4:0"); 
        new Game("Bundesliga 22/23", 5, "FC Augsburg", "Hertha BSC", "0:2"); 
        new Game("Bundesliga 22/23", 5, "Borussia Mönchengladbach", "1. FSV Mainz 05", "0:1"); 
        new Game("Bundesliga 22/23", 6, "SV Werder Bremen", "FC Augsburg", "0:1"); 
        new Game("Bundesliga 22/23", 6, "FC Bayern München", "VfB Stuttgart", "2:2"); 
        new Game("Bundesliga 22/23", 6, "RB Leipzig", "Borussia Dortmund", "3:0"); 
        new Game("Bundesliga 22/23", 6, "1899 Hoffenheim", "1. FSV Mainz 05", "4:1"); 
        new Game("Bundesliga 22/23", 6, "Eintracht Frankfurt", "VfL Wolfsburg", "0:1"); 
        new Game("Bundesliga 22/23", 6, "Hertha BSC", "Bayer Leverkusen", "2:2"); 
        new Game("Bundesliga 22/23", 6, "FC Schalke 04", "VfL Bochum", "3:1"); 
        new Game("Bundesliga 22/23", 6, "1. FC Köln", "1. FC Union Berlin", "0:1"); 
        new Game("Bundesliga 22/23", 6, "SC Freiburg", "Borussia Mönchengladbach", "0:0"); 
        new Game("Bundesliga 22/23", 7, "1. FSV Mainz 05", "Hertha BSC", "1:1"); 
        new Game("Bundesliga 22/23", 7, "FC Augsburg", "FC Bayern München", "1:0"); 
        new Game("Bundesliga 22/23", 7, "Bayer Leverkusen", "SV Werder Bremen", "1:1"); 
        new Game("Bundesliga 22/23", 7, "VfB Stuttgart", "Eintracht Frankfurt", "1:3"); 
        new Game("Bundesliga 22/23", 7, "Borussia Dortmund", "FC Schalke 04", "1:0"); 
        new Game("Bundesliga 22/23", 7, "Borussia Mönchengladbach", "RB Leipzig", "3:0"); 
        new Game("Bundesliga 22/23", 7, "1. FC Union Berlin", "VfL Wolfsburg", "2:0"); 
        new Game("Bundesliga 22/23", 7, "VfL Bochum", "1. FC Köln", "1:1"); 
        new Game("Bundesliga 22/23", 7, "1899 Hoffenheim", "SC Freiburg", "0:0"); 
        new Game("Bundesliga 22/23", 8, "FC Bayern München", "Bayer Leverkusen", "4:0"); 
        new Game("Bundesliga 22/23", 8, "RB Leipzig", "VfL Bochum", "4:0"); 
        new Game("Bundesliga 22/23", 8, "SC Freiburg", "1. FSV Mainz 05", "2:1"); 
        new Game("Bundesliga 22/23", 8, "1. FC Köln", "Borussia Dortmund", "3:2"); 
        new Game("Bundesliga 22/23", 8, "Eintracht Frankfurt", "1. FC Union Berlin", "2:0"); 
        new Game("Bundesliga 22/23", 8, "VfL Wolfsburg", "VfB Stuttgart", "3:2"); 
        new Game("Bundesliga 22/23", 8, "SV Werder Bremen", "Borussia Mönchengladbach", "5:1"); 
        new Game("Bundesliga 22/23", 8, "Hertha BSC", "1899 Hoffenheim", "1:1"); 
        new Game("Bundesliga 22/23", 8, "FC Schalke 04", "FC Augsburg", "2:3"); 
        new Game("Bundesliga 22/23", 9, "1899 Hoffenheim", "SV Werder Bremen", "1:2"); 
        new Game("Bundesliga 22/23", 9, "Bayer Leverkusen", "FC Schalke 04", "4:0"); 
        new Game("Bundesliga 22/23", 9, "1. FSV Mainz 05", "RB Leipzig", "1:1"); 
        new Game("Bundesliga 22/23", 9, "VfL Bochum", "Eintracht Frankfurt", "3:0"); 
        new Game("Bundesliga 22/23", 9, "FC Augsburg", "VfL Wolfsburg", "1:1"); 
        new Game("Bundesliga 22/23", 9, "Borussia Dortmund", "FC Bayern München", "2:2"); 
        new Game("Bundesliga 22/23", 9, "Borussia Mönchengladbach", "1. FC Köln", "5:2"); 
        new Game("Bundesliga 22/23", 9, "Hertha BSC", "SC Freiburg", "2:2"); 
        new Game("Bundesliga 22/23", 9, "VfB Stuttgart", "1. FC Union Berlin", "0:1"); 
        new Game("Bundesliga 22/23", 10, "FC Schalke 04", "1899 Hoffenheim", "0:3"); 
        new Game("Bundesliga 22/23", 10, "Eintracht Frankfurt", "Bayer Leverkusen", "5:1"); 
        new Game("Bundesliga 22/23", 10, "VfL Wolfsburg", "Borussia Mönchengladbach", "2:2"); 
        new Game("Bundesliga 22/23", 10, "VfB Stuttgart", "VfL Bochum", "4:1"); 
        new Game("Bundesliga 22/23", 10, "SV Werder Bremen", "1. FSV Mainz 05", "0:2"); 
        new Game("Bundesliga 22/23", 10, "RB Leipzig", "Hertha BSC", "3:2"); 
        new Game("Bundesliga 22/23", 10, "1. FC Köln", "FC Augsburg", "3:2"); 
        new Game("Bundesliga 22/23", 10, "1. FC Union Berlin", "Borussia Dortmund", "2:0"); 
        new Game("Bundesliga 22/23", 10, "FC Bayern München", "SC Freiburg", "5:0"); 
        new Game("Bundesliga 22/23", 11, "1. FSV Mainz 05", "1. FC Köln", "5:0"); 
        new Game("Bundesliga 22/23", 11, "Borussia Dortmund", "VfB Stuttgart", "5:0"); 
        new Game("Bundesliga 22/23", 11, "Bayer Leverkusen", "VfL Wolfsburg", "2:2"); 
        new Game("Bundesliga 22/23", 11, "SC Freiburg", "SV Werder Bremen", "2:0"); 
        new Game("Bundesliga 22/23", 11, "1899 Hoffenheim", "FC Bayern München", "0:2"); 
        new Game("Bundesliga 22/23", 11, "FC Augsburg", "RB Leipzig", "3:3"); 
        new Game("Bundesliga 22/23", 11, "Borussia Mönchengladbach", "Eintracht Frankfurt", "1:3"); 
        new Game("Bundesliga 22/23", 11, "VfL Bochum", "1. FC Union Berlin", "2:1"); 
        new Game("Bundesliga 22/23", 11, "Hertha BSC", "FC Schalke 04", "2:1"); 
        new Game("Bundesliga 22/23", 12, "SV Werder Bremen", "Hertha BSC", "1:0"); 
        new Game("Bundesliga 22/23", 12, "FC Bayern München", "1. FSV Mainz 05", "6:2"); 
        new Game("Bundesliga 22/23", 12, "RB Leipzig", "Bayer Leverkusen", "2:0"); 
        new Game("Bundesliga 22/23", 12, "VfL Wolfsburg", "VfL Bochum", "4:0"); 
        new Game("Bundesliga 22/23", 12, "VfB Stuttgart", "FC Augsburg", "2:1"); 
        new Game("Bundesliga 22/23", 12, "Eintracht Frankfurt", "Borussia Dortmund", "1:2"); 
        new Game("Bundesliga 22/23", 12, "1. FC Union Berlin", "Borussia Mönchengladbach", "2:1"); 
        new Game("Bundesliga 22/23", 12, "FC Schalke 04", "SC Freiburg", "0:2"); 
        new Game("Bundesliga 22/23", 12, "1. FC Köln", "1899 Hoffenheim", "1:1"); 
        new Game("Bundesliga 22/23", 13, "Borussia Mönchengladbach", "VfB Stuttgart", "3:1"); 
        new Game("Bundesliga 22/23", 13, "Borussia Dortmund", "VfL Bochum", "3:0"); 
        new Game("Bundesliga 22/23", 13, "1. FSV Mainz 05", "VfL Wolfsburg", "0:3"); 
        new Game("Bundesliga 22/23", 13, "1899 Hoffenheim", "RB Leipzig", "1:3"); 
        new Game("Bundesliga 22/23", 13, "FC Augsburg", "Eintracht Frankfurt", "1:2"); 
        new Game("Bundesliga 22/23", 13, "Hertha BSC", "FC Bayern München", "2:3"); 
        new Game("Bundesliga 22/23", 13, "SV Werder Bremen", "FC Schalke 04", "2:1"); 
        new Game("Bundesliga 22/23", 13, "Bayer Leverkusen", "1. FC Union Berlin", "5:0"); 
        new Game("Bundesliga 22/23", 13, "SC Freiburg", "1. FC Köln", "2:0"); 
        new Game("Bundesliga 22/23", 14, "1. FC Köln", "Bayer Leverkusen", "1:2"); 
        new Game("Bundesliga 22/23", 14, "RB Leipzig", "SC Freiburg", "3:1"); 
        new Game("Bundesliga 22/23", 14, "1. FC Union Berlin", "FC Augsburg", "2:2"); 
        new Game("Bundesliga 22/23", 14, "Eintracht Frankfurt", "1899 Hoffenheim", "4:2"); 
        new Game("Bundesliga 22/23", 14, "FC Schalke 04", "1. FSV Mainz 05", "1:0"); 
        new Game("Bundesliga 22/23", 14, "VfL Wolfsburg", "Borussia Dortmund", "2:0"); 
        new Game("Bundesliga 22/23", 14, "FC Bayern München", "SV Werder Bremen", "6:1"); 
        new Game("Bundesliga 22/23", 14, "VfL Bochum", "Borussia Mönchengladbach", "2:1"); 
        new Game("Bundesliga 22/23", 14, "VfB Stuttgart", "Hertha BSC", "2:1"); 
        new Game("Bundesliga 22/23", 15, "Borussia Mönchengladbach", "Borussia Dortmund", "4:2"); 
        new Game("Bundesliga 22/23", 15, "Bayer Leverkusen", "VfB Stuttgart", "2:0"); 
        new Game("Bundesliga 22/23", 15, "1899 Hoffenheim", "VfL Wolfsburg", "1:2"); 
        new Game("Bundesliga 22/23", 15, "FC Augsburg", "VfL Bochum", "0:1"); 
        new Game("Bundesliga 22/23", 15, "Hertha BSC", "1. FC Köln", "2:0"); 
        new Game("Bundesliga 22/23", 15, "SV Werder Bremen", "RB Leipzig", "1:2"); 
        new Game("Bundesliga 22/23", 15, "FC Schalke 04", "FC Bayern München", "0:2"); 
        new Game("Bundesliga 22/23", 15, "1. FSV Mainz 05", "Eintracht Frankfurt", "1:1"); 
        new Game("Bundesliga 22/23", 15, "SC Freiburg", "1. FC Union Berlin", "4:1"); 
        new Game("Bundesliga 22/23", 16, "RB Leipzig", "FC Bayern München", "1:1"); 
        new Game("Bundesliga 22/23", 16, "1. FC Union Berlin", "1899 Hoffenheim", "3:1"); 
        new Game("Bundesliga 22/23", 16, "Eintracht Frankfurt", "FC Schalke 04", "3:0"); 
        new Game("Bundesliga 22/23", 16, "VfL Wolfsburg", "SC Freiburg", "6:0"); 
        new Game("Bundesliga 22/23", 16, "VfL Bochum", "Hertha BSC", "3:1"); 
        new Game("Bundesliga 22/23", 16, "VfB Stuttgart", "1. FSV Mainz 05", "1:1"); 
        new Game("Bundesliga 22/23", 16, "1. FC Köln", "SV Werder Bremen", "7:1"); 
        new Game("Bundesliga 22/23", 16, "Borussia Dortmund", "FC Augsburg", "4:3"); 
        new Game("Bundesliga 22/23", 16, "Borussia Mönchengladbach", "Bayer Leverkusen", "2:3"); 
        new Game("Bundesliga 22/23", 17, "FC Schalke 04", "RB Leipzig", "1:6"); 
        new Game("Bundesliga 22/23", 17, "FC Bayern München", "1. FC Köln", "1:1"); 
        new Game("Bundesliga 22/23", 17, "1899 Hoffenheim", "VfB Stuttgart", "2:2"); 
        new Game("Bundesliga 22/23", 17, "Hertha BSC", "VfL Wolfsburg", "0:5"); 
        new Game("Bundesliga 22/23", 17, "1. FSV Mainz 05", "Borussia Dortmund", "1:2"); 
        new Game("Bundesliga 22/23", 17, "Bayer Leverkusen", "VfL Bochum", "2:0"); 
        new Game("Bundesliga 22/23", 17, "SC Freiburg", "Eintracht Frankfurt", "1:1"); 
        new Game("Bundesliga 22/23", 17, "FC Augsburg", "Borussia Mönchengladbach", "1:0"); 
        new Game("Bundesliga 22/23", 17, "SV Werder Bremen", "1. FC Union Berlin", "1:2"); 
        new Game("Bundesliga 22/23", 18, "RB Leipzig", "VfB Stuttgart", "2:1"); 
        new Game("Bundesliga 22/23", 18, "SC Freiburg", "FC Augsburg", "3:1"); 
        new Game("Bundesliga 22/23", 18, "1. FSV Mainz 05", "VfL Bochum", "5:2"); 
        new Game("Bundesliga 22/23", 18, "1899 Hoffenheim", "Borussia Mönchengladbach", "1:4"); 
        new Game("Bundesliga 22/23", 18, "Hertha BSC", "1. FC Union Berlin", "0:2"); 
        new Game("Bundesliga 22/23", 18, "SV Werder Bremen", "VfL Wolfsburg", "2:1"); 
        new Game("Bundesliga 22/23", 18, "FC Bayern München", "Eintracht Frankfurt", "1:1"); 
        new Game("Bundesliga 22/23", 18, "FC Schalke 04", "1. FC Köln", "0:0"); 
        new Game("Bundesliga 22/23", 18, "Bayer Leverkusen", "Borussia Dortmund", "0:2"); 
        new Game("Bundesliga 22/23", 19, "FC Augsburg", "Bayer Leverkusen", "1:0"); 
        new Game("Bundesliga 22/23", 19, "Borussia Dortmund", "SC Freiburg", "5:1"); 
        new Game("Bundesliga 22/23", 19, "1. FC Union Berlin", "1. FSV Mainz 05", "2:1"); 
        new Game("Bundesliga 22/23", 19, "1. FC Köln", "RB Leipzig", "0:0"); 
        new Game("Bundesliga 22/23", 19, "Eintracht Frankfurt", "Hertha BSC", "3:0"); 
        new Game("Bundesliga 22/23", 19, "VfL Bochum", "1899 Hoffenheim", "5:2"); 
        new Game("Bundesliga 22/23", 19, "Borussia Mönchengladbach", "FC Schalke 04", "0:0"); 
        new Game("Bundesliga 22/23", 19, "VfB Stuttgart", "SV Werder Bremen", "0:2"); 
        new Game("Bundesliga 22/23", 19, "VfL Wolfsburg", "FC Bayern München", "2:4"); 
        new Game("Bundesliga 22/23", 20, "FC Bayern München", "VfL Bochum", "3:0"); 
        new Game("Bundesliga 22/23", 20, "RB Leipzig", "1. FC Union Berlin", "1:2"); 
        new Game("Bundesliga 22/23", 20, "SC Freiburg", "VfB Stuttgart", "2:1"); 
        new Game("Bundesliga 22/23", 20, "1. FC Köln", "Eintracht Frankfurt", "3:0"); 
        new Game("Bundesliga 22/23", 20, "1. FSV Mainz 05", "FC Augsburg", "3:1"); 
        new Game("Bundesliga 22/23", 20, "1899 Hoffenheim", "Bayer Leverkusen", "1:3"); 
        new Game("Bundesliga 22/23", 20, "Hertha BSC", "Borussia Mönchengladbach", "4:1"); 
        new Game("Bundesliga 22/23", 20, "FC Schalke 04", "VfL Wolfsburg", "0:0"); 
        new Game("Bundesliga 22/23", 20, "SV Werder Bremen", "Borussia Dortmund", "0:2"); 
        new Game("Bundesliga 22/23", 21, "Borussia Dortmund", "Hertha BSC", "4:1"); 
        new Game("Bundesliga 22/23", 21, "Bayer Leverkusen", "1. FSV Mainz 05", "2:3"); 
        new Game("Bundesliga 22/23", 21, "1. FC Union Berlin", "FC Schalke 04", "0:0"); 
        new Game("Bundesliga 22/23", 21, "Borussia Mönchengladbach", "FC Bayern München", "3:2"); 
        new Game("Bundesliga 22/23", 21, "Eintracht Frankfurt", "SV Werder Bremen", "2:0"); 
        new Game("Bundesliga 22/23", 21, "VfL Wolfsburg", "RB Leipzig", "0:3"); 
        new Game("Bundesliga 22/23", 21, "VfL Bochum", "SC Freiburg", "0:2"); 
        new Game("Bundesliga 22/23", 21, "FC Augsburg", "1899 Hoffenheim", "1:0"); 
        new Game("Bundesliga 22/23", 21, "VfB Stuttgart", "1. FC Köln", "3:0"); 
        new Game("Bundesliga 22/23", 22, "FC Bayern München", "1. FC Union Berlin", "3:0"); 
        new Game("Bundesliga 22/23", 22, "RB Leipzig", "Eintracht Frankfurt", "2:1"); 
        new Game("Bundesliga 22/23", 22, "SC Freiburg", "Bayer Leverkusen", "1:1"); 
        new Game("Bundesliga 22/23", 22, "1. FC Köln", "VfL Wolfsburg", "0:2"); 
        new Game("Bundesliga 22/23", 22, "1. FSV Mainz 05", "Borussia Mönchengladbach", "4:0"); 
        new Game("Bundesliga 22/23", 22, "1899 Hoffenheim", "Borussia Dortmund", "0:1"); 
        new Game("Bundesliga 22/23", 22, "Hertha BSC", "FC Augsburg", "2:0"); 
        new Game("Bundesliga 22/23", 22, "FC Schalke 04", "VfB Stuttgart", "2:1"); 
        new Game("Bundesliga 22/23", 22, "SV Werder Bremen", "VfL Bochum", "3:0"); 
        new Game("Bundesliga 22/23", 23, "Borussia Dortmund", "RB Leipzig", "2:1"); 
        new Game("Bundesliga 22/23", 23, "Bayer Leverkusen", "Hertha BSC", "4:1"); 
        new Game("Bundesliga 22/23", 23, "1. FC Union Berlin", "1. FC Köln", "0:0"); 
        new Game("Bundesliga 22/23", 23, "1. FSV Mainz 05", "1899 Hoffenheim", "1:0"); 
        new Game("Bundesliga 22/23", 23, "Borussia Mönchengladbach", "SC Freiburg", "0:0"); 
        new Game("Bundesliga 22/23", 23, "VfL Wolfsburg", "Eintracht Frankfurt", "2:2"); 
        new Game("Bundesliga 22/23", 23, "VfL Bochum", "FC Schalke 04", "0:2"); 
        new Game("Bundesliga 22/23", 23, "FC Augsburg", "SV Werder Bremen", "2:1"); 
        new Game("Bundesliga 22/23", 23, "VfB Stuttgart", "FC Bayern München", "1:2"); 
        new Game("Bundesliga 22/23", 24, "FC Bayern München", "FC Augsburg", "5:3"); 
        new Game("Bundesliga 22/23", 24, "RB Leipzig", "Borussia Mönchengladbach", "3:0"); 
        new Game("Bundesliga 22/23", 24, "SC Freiburg", "1899 Hoffenheim", "2:1"); 
        new Game("Bundesliga 22/23", 24, "1. FC Köln", "VfL Bochum", "0:2"); 
        new Game("Bundesliga 22/23", 24, "Eintracht Frankfurt", "VfB Stuttgart", "1:1"); 
        new Game("Bundesliga 22/23", 24, "VfL Wolfsburg", "1. FC Union Berlin", "1:1"); 
        new Game("Bundesliga 22/23", 24, "Hertha BSC", "1. FSV Mainz 05", "1:1"); 
        new Game("Bundesliga 22/23", 24, "FC Schalke 04", "Borussia Dortmund", "2:2"); 
        new Game("Bundesliga 22/23", 24, "SV Werder Bremen", "Bayer Leverkusen", "2:3"); 
        new Game("Bundesliga 22/23", 25, "Borussia Dortmund", "1. FC Köln", "6:1"); 
        new Game("Bundesliga 22/23", 25, "Bayer Leverkusen", "FC Bayern München", "2:1"); 
        new Game("Bundesliga 22/23", 25, "1. FC Union Berlin", "Eintracht Frankfurt", "2:0"); 
        new Game("Bundesliga 22/23", 25, "1. FSV Mainz 05", "SC Freiburg", "1:1"); 
        new Game("Bundesliga 22/23", 25, "1899 Hoffenheim", "Hertha BSC", "3:1"); 
        new Game("Bundesliga 22/23", 25, "Borussia Mönchengladbach", "SV Werder Bremen", "2:2"); 
        new Game("Bundesliga 22/23", 25, "VfL Bochum", "RB Leipzig", "1:0"); 
        new Game("Bundesliga 22/23", 25, "FC Augsburg", "FC Schalke 04", "1:1"); 
        new Game("Bundesliga 22/23", 25, "VfB Stuttgart", "VfL Wolfsburg", "0:1"); 
        new Game("Bundesliga 22/23", 26, "FC Bayern München", "Borussia Dortmund", "4:2"); 
        new Game("Bundesliga 22/23", 26, "RB Leipzig", "1. FSV Mainz 05", "0:3"); 
        new Game("Bundesliga 22/23", 26, "1. FC Union Berlin", "VfB Stuttgart", "3:0"); 
        new Game("Bundesliga 22/23", 26, "SC Freiburg", "Hertha BSC", "1:1"); 
        new Game("Bundesliga 22/23", 26, "1. FC Köln", "Borussia Mönchengladbach", "0:0"); 
        new Game("Bundesliga 22/23", 26, "Eintracht Frankfurt", "VfL Bochum", "1:1"); 
        new Game("Bundesliga 22/23", 26, "VfL Wolfsburg", "FC Augsburg", "2:2"); 
        new Game("Bundesliga 22/23", 26, "FC Schalke 04", "Bayer Leverkusen", "0:3"); 
        new Game("Bundesliga 22/23", 26, "SV Werder Bremen", "1899 Hoffenheim", "1:2"); 
        new Game("Bundesliga 22/23", 27, "Borussia Dortmund", "1. FC Union Berlin", "2:1"); 
        new Game("Bundesliga 22/23", 27, "Bayer Leverkusen", "Eintracht Frankfurt", "3:1"); 
        new Game("Bundesliga 22/23", 27, "SC Freiburg", "FC Bayern München", "0:1"); 
        new Game("Bundesliga 22/23", 27, "1. FSV Mainz 05", "SV Werder Bremen", "2:2"); 
        new Game("Bundesliga 22/23", 27, "1899 Hoffenheim", "FC Schalke 04", "2:0"); 
        new Game("Bundesliga 22/23", 27, "Borussia Mönchengladbach", "VfL Wolfsburg", "2:0"); 
        new Game("Bundesliga 22/23", 27, "VfL Bochum", "VfB Stuttgart", "2:3"); 
        new Game("Bundesliga 22/23", 27, "FC Augsburg", "1. FC Köln", "1:3"); 
        new Game("Bundesliga 22/23", 27, "Hertha BSC", "RB Leipzig", "0:1"); 
        new Game("Bundesliga 22/23", 28, "FC Bayern München", "1899 Hoffenheim", "1:1"); 
        new Game("Bundesliga 22/23", 28, "RB Leipzig", "FC Augsburg", "3:2"); 
        new Game("Bundesliga 22/23", 28, "1. FC Union Berlin", "VfL Bochum", "1:1"); 
        new Game("Bundesliga 22/23", 28, "1. FC Köln", "1. FSV Mainz 05", "1:1"); 
        new Game("Bundesliga 22/23", 28, "Eintracht Frankfurt", "Borussia Mönchengladbach", "1:1"); 
        new Game("Bundesliga 22/23", 28, "VfL Wolfsburg", "Bayer Leverkusen", "0:0"); 
        new Game("Bundesliga 22/23", 28, "VfB Stuttgart", "Borussia Dortmund", "3:3"); 
        new Game("Bundesliga 22/23", 28, "FC Schalke 04", "Hertha BSC", "5:2"); 
        new Game("Bundesliga 22/23", 28, "SV Werder Bremen", "SC Freiburg", "1:2"); 
        new Game("Bundesliga 22/23", 29, "Borussia Dortmund", "Eintracht Frankfurt", "4:0"); 
        new Game("Bundesliga 22/23", 29, "Bayer Leverkusen", "RB Leipzig", "2:0"); 
        new Game("Bundesliga 22/23", 29, "SC Freiburg", "FC Schalke 04", "4:0"); 
        new Game("Bundesliga 22/23", 29, "1. FSV Mainz 05", "FC Bayern München", "3:1"); 
        new Game("Bundesliga 22/23", 29, "1899 Hoffenheim", "1. FC Köln", "1:3"); 
        new Game("Bundesliga 22/23", 29, "Borussia Mönchengladbach", "1. FC Union Berlin", "0:1"); 
        new Game("Bundesliga 22/23", 29, "VfL Bochum", "VfL Wolfsburg", "1:5"); 
        new Game("Bundesliga 22/23", 29, "FC Augsburg", "VfB Stuttgart", "1:1"); 
        new Game("Bundesliga 22/23", 29, "Hertha BSC", "SV Werder Bremen", "2:4"); 
        new Game("Bundesliga 22/23", 30, "FC Bayern München", "Hertha BSC", "2:0"); 
        new Game("Bundesliga 22/23", 30, "RB Leipzig", "1899 Hoffenheim", "1:0"); 
        new Game("Bundesliga 22/23", 30, "1. FC Union Berlin", "Bayer Leverkusen", "0:0"); 
        new Game("Bundesliga 22/23", 30, "1. FC Köln", "SC Freiburg", "0:1"); 
        new Game("Bundesliga 22/23", 30, "Eintracht Frankfurt", "FC Augsburg", "1:1"); 
        new Game("Bundesliga 22/23", 30, "VfL Wolfsburg", "1. FSV Mainz 05", "3:0"); 
        new Game("Bundesliga 22/23", 30, "VfL Bochum", "Borussia Dortmund", "1:1"); 
        new Game("Bundesliga 22/23", 30, "VfB Stuttgart", "Borussia Mönchengladbach", "2:1"); 
        new Game("Bundesliga 22/23", 30, "FC Schalke 04", "SV Werder Bremen", "2:1"); 
        new Game("Bundesliga 22/23", 31, "Borussia Dortmund", "VfL Wolfsburg", "6:0"); 
        new Game("Bundesliga 22/23", 31, "Bayer Leverkusen", "1. FC Köln", "1:2"); 
        new Game("Bundesliga 22/23", 31, "SC Freiburg", "RB Leipzig", "0:1"); 
        new Game("Bundesliga 22/23", 31, "1. FSV Mainz 05", "FC Schalke 04", "2:3"); 
        new Game("Bundesliga 22/23", 31, "1899 Hoffenheim", "Eintracht Frankfurt", "3:1"); 
        new Game("Bundesliga 22/23", 31, "Borussia Mönchengladbach", "VfL Bochum", "2:0"); 
        new Game("Bundesliga 22/23", 31, "FC Augsburg", "1. FC Union Berlin", "1:0"); 
        new Game("Bundesliga 22/23", 31, "Hertha BSC", "VfB Stuttgart", "2:1"); 
        new Game("Bundesliga 22/23", 31, "SV Werder Bremen", "FC Bayern München", "1:2"); 
        new Game("Bundesliga 22/23", 32, "FC Bayern München", "FC Schalke 04", "6:0"); 
        new Game("Bundesliga 22/23", 32, "Borussia Dortmund", "Borussia Mönchengladbach", "5:2"); 
        new Game("Bundesliga 22/23", 32, "RB Leipzig", "SV Werder Bremen", "2:1"); 
        new Game("Bundesliga 22/23", 32, "1. FC Union Berlin", "SC Freiburg", "4:2"); 
        new Game("Bundesliga 22/23", 32, "1. FC Köln", "Hertha BSC", "5:2"); 
        new Game("Bundesliga 22/23", 32, "Eintracht Frankfurt", "1. FSV Mainz 05", "3:0"); 
        new Game("Bundesliga 22/23", 32, "VfL Wolfsburg", "1899 Hoffenheim", "2:1"); 
        new Game("Bundesliga 22/23", 32, "VfL Bochum", "FC Augsburg", "3:2"); 
        new Game("Bundesliga 22/23", 32, "VfB Stuttgart", "Bayer Leverkusen", "1:1"); 
        new Game("Bundesliga 22/23", 33, "FC Bayern München", "RB Leipzig", "1:3"); 
        new Game("Bundesliga 22/23", 33, "Bayer Leverkusen", "Borussia Mönchengladbach", "2:2"); 
        new Game("Bundesliga 22/23", 33, "SC Freiburg", "VfL Wolfsburg", "2:0"); 
        new Game("Bundesliga 22/23", 33, "1. FSV Mainz 05", "VfB Stuttgart", "1:4"); 
        new Game("Bundesliga 22/23", 33, "1899 Hoffenheim", "1. FC Union Berlin", "4:2"); 
        new Game("Bundesliga 22/23", 33, "FC Augsburg", "Borussia Dortmund", "0:3"); 
        new Game("Bundesliga 22/23", 33, "Hertha BSC", "VfL Bochum", "1:1"); 
        new Game("Bundesliga 22/23", 33, "FC Schalke 04", "Eintracht Frankfurt", "2:2"); 
        new Game("Bundesliga 22/23", 33, "SV Werder Bremen", "1. FC Köln", "1:1"); 
        new Game("Bundesliga 22/23", 34, "Borussia Dortmund", "1. FSV Mainz 05", "2:2"); 
        new Game("Bundesliga 22/23", 34, "RB Leipzig", "FC Schalke 04", "4:2"); 
        new Game("Bundesliga 22/23", 34, "1. FC Union Berlin", "SV Werder Bremen", "1:0"); 
        new Game("Bundesliga 22/23", 34, "1. FC Köln", "FC Bayern München", "1:2"); 
        new Game("Bundesliga 22/23", 34, "Borussia Mönchengladbach", "FC Augsburg", "2:0"); 
        new Game("Bundesliga 22/23", 34, "Eintracht Frankfurt", "SC Freiburg", "2:1"); 
        new Game("Bundesliga 22/23", 34, "VfL Wolfsburg", "Hertha BSC", "1:2"); 
        new Game("Bundesliga 22/23", 34, "VfL Bochum", "Bayer Leverkusen", "3:0"); 
        new Game("Bundesliga 22/23", 34, "VfB Stuttgart", "1899 Hoffenheim", "1:1"); 
    }
 
}
